[phases.install]
cmds = [
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "mkdir -p bootstrap/cache storage/logs storage/framework/cache storage/framework/sessions storage/framework/views public/build",
  "chmod -R 775 bootstrap/cache storage public/build",
  "composer install --ignore-platform-reqs",
  "npm i"
]

[phases.build]
cmds = [
  "npm run build"
]
